env:
  browser: true
  es6: true
extends: 'eslint:recommended'
parserOptions:
  ecmaFeatures:
    jsx: true
    experimentalObjectRestSpread: true
  sourceType: module
plugins:
  - inferno
rules:
  inferno/jsx-uses-inferno: error
  inferno/jsx-uses-vars: error
  no-console: 0
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - backtick
  semi:
    - error
    - never
